# development stage image
FROM node:22-alpine as dev

# Set the working directory
WORKDIR /app

COPY package.json ./

RUN npm install

# Copy the rest of the application
COPY . .

CMD ["npm", "start"]

# build stage image
FROM node:22-alpine as build

# Set the working directory
WORKDIR /app

COPY package.json ./

RUN npm install

# Copy the rest of the application
COPY . .

RUN npm run build

# production stage image
FROM nginx:alpine as production

# Copy the build files to the nginx server
COPY --from=build /app/build /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]