# development stage image
FROM node:22-alpine as dev

# Set the working directory
WORKDIR /app

COPY package.json ./

RUN npm install

# Copy the rest of the application
COPY . .

CMD ["npx", "nodemon", "index.js"]

# production stage image
FROM node:22-alpine as prod

# Set the working directory
WORKDIR /app

COPY package.json ./

RUN npm install

# Copy the rest of the application
COPY . .

CMD ["nodemon", "index.js"]